    zn "%SYS"
    Do ##class(Security.Users).UnExpireUserPasswords("*")

    ; enabling callin for Embedded Python
    do ##class(Security.Services).Get("%Service_CallIn",.prop)
    set prop("Enabled")=1
    set prop("AutheEnabled")=48
    do ##class(Security.Services).Modify("%Service_CallIn",.prop)

    zn "IRISAPP"
    zpm "load /home/irisowner/dev/ -v":1:1
    ;do $system.OBJ.LoadDir("/home/irisowner/dev/src/cls","cuk",,1)
    halt
